remove calls to projectm text helpers that are no longer available
projectM-visualizer/frontend-sdl2 pull request #44
Opened 2022-11-12 17:43 UTC by nzoschke

Fixes #43

TODO:

- [ ] Log text
- [ ] Render text in SDL frontend?

2022-11-13 16:12 UTC, nzoschke commented
CC @kblaschke based on your comment on https://github.com/projectM-visualizer/projectm/pull/652

> Also note this commit will break the rewritten SDL2 frontend for now, but that's fine. I'll fix that after the API changes are finished.

If you have a branch of `frontend-sdl2` that addresses this I'm happy to review and work off that. 

But I think it would be nice to get master / master building again to base other frontend improvements on.

2022-11-13 16:12 UTC, nzoschke commented on src/RenderLoop.cpp
> +            SDL_LogInfo(SDL_LOG_CATEGORY_APPLICATION, aspectCorrectionEnabled ? "Aspect Correction Enabled" : "Aspect Correction Disabled");
is there a line length enforced in the repo?

2022-11-14 15:48 UTC, kblaschke commented
I've not yet started to refactor the frontend, besauce there are plenty more API changes to come, e.g. moving the playlist functionality into another library with different API functions.

We can keep this PR open and keep it in sync to the ongoing changes in the main repo though, this will probably help some people to build the application against the latest upstream master. When the API changes are done, simply merge the PR and that's it.

2022-11-14 15:56 UTC, nzoschke commented
Ok That works for me. 

I'm able to maintain my own front end fork no problem for now. 

Just sharing some of the pieces in case it helps others.

2022-11-14 15:56 UTC, kblaschke requested changes

2022-11-14 15:56 UTC, kblaschke commented on src/RenderLoop.cpp
> +            SDL_LogInfo(SDL_LOG_CATEGORY_APPLICATION, aspectCorrectionEnabled ? "Aspect Correction Enabled" : "Aspect Correction Disabled");
Please use the POCO logging macros, otherwise the application will output stuff in two different places.

2023-01-17 19:39 UTC, kblaschke commented
Opened another PR with a large number of other required changes, as libprojectM changed some more in the meantime.

Closing this PR, as the same change is also in the other one.

2023-01-17 19:39 UTC, closed without merging